### ISSUE TITLE
如何处理客户端权限

### ISSUE THREAD

**Issue by mingliao** [bailicangdu/vue2-manage#1]
您好，感谢您提供仿饿了么客户端源码，正在学习中，受益匪浅，
请教一个问题，就是如何做客户端权限认证？

我看过一些关于jwt的介绍，就是用户登录之后，利用账号，密码换取服务端的一个token信息，客户端保存好这个token信息，每次请求服务端资源的时候，在头部发送这个token到服务端，可以获取用户的角色role信息，
根据角色去获取服务端资源，如果用户授权有问题，就不能获取相应的资源。

不过我现在碰到的问题是，前后端分离的单页应用程序(前端负责渲染页面，后端提供api[后端不提供页面渲染，不使用模板渲染])能否利用这个token或者用什么技术做客户端权限认证，
因为可能有这些场景，
1，一些角色要访问特定的页面，如果游客访问系统管理员的页面，客户端跳转401页面；
2，具体某个页面上，不同角色要显示不同按钮。但是这些可能都不走服务端，直接在客户端处理完成。能否让客户端维护自己的权限处理方式。

对于客户端权限问题，您有没有什么好的建议，
或者您将会在这个系统中使用vue auth的相关技术。感谢指导。谢谢。

**Comment by bailicangdu** [comment]
前后端分离也可以用token做用户验证。这个验证的过程不需要前端做任何事情，后台会进行判断。前台可以用localstorage记录用户的状态，但这并不稳定，也不建议这样做，最好的方式还是通过后台验证

**Comment by mingliao** [comment]
请教下， 比如我用vue-route 做客户端跳转，游客自己在地址栏自己输入一个管理员页面的url，从a页面跳转到b页面，
1.您的做法是先让客户端先跳转到b页面，然后在b页面发送一个请求（在生命周期create的时候去发出这个请求），判断用户是否有权限访问这个b页面，如果没有权限的话，返回给客户端未授权提示信息，再做跳转么？
2.还是直接在vue-route里面通过某种方式对url做拦截，在header里面加入token，然后给服务端发送请求，如果请求不合法，直接跳转401页面，客户端没有办法跑到b页面去？
或者是不是还有别的方式？

**Comment by bailicangdu** [comment]
显然第二种方式更好

**Comment by mingliao** [comment]
好，谢了。碰到问题再请教。
