### ISSUE TITLE
我拉下来登录页没有注册，只有登录，我怎么注册？

### ISSUE THREAD

**Issue by wangchong19940101** [bailicangdu/vue2-manage#103]
![image](https://user-images.githubusercontent.com/30942709/50889889-05393180-1434-11e9-9dc2-99d231a2718c.png)

**Comment by bailicangdu** [comment]
随便输入账号密码，如果没有人注册过会自动注册。下面有红字提示

**Comment by wangchong19940101** [comment]
ok
