### ISSUE TITLE
应该是缺少一个登录认证吧。

### ISSUE THREAD

**Issue by fanerge** [bailicangdu/vue2-manage#15]
我在一个浏览器中登录了并进入了http://localhost:8002/#/manage，然后我在另一个浏览器中直接复制http://localhost:8002/#/manage居然没有登录就进入了页面。

**Comment by zhaohxfight** [comment]
对是缺少登录验证的，需要在借口判断cookie 里面是否有session 或者根据后台请求状态 来跳转到登录页面

**Comment by zhaohxfight** [comment]
包括 登录验证 还有管理员权限 等 都可以在每次请求的时候通过 session 传到后台 后台判断完成一些 验证或者权限的问题。 然后再封装好的请求js 里面加入状态判断。
