### ISSUE TITLE
后台管理系统退出登陆报错

### ISSUE THREAD

**Issue by ZhichaoOuyang** [bailicangdu/vue2-manage#164]
是用dev方式跑的线上的。提示404，刚入门小白求解。
![image](https://user-images.githubusercontent.com/51399917/76329021-fa737880-6326-11ea-9a7d-35eb3d106dc0.png)

**Comment by bailicangdu** [comment]
应该是代理的问题，没有找到接口

**Comment by ZhichaoOuyang** [comment]
> 应该是代理的问题，没有找到接口

你好，请问有什么办法解决吗？我挂了vpn也不行。

**Comment by Shulaolao** [comment]
@bailicangdu 大佬这种代理要咋做呢，真找不到源码代理处
