### ISSUE TITLE
大佬，仿饿了么移动端的接口都挂了

### ISSUE THREAD

**Issue by Barryhuan** [bailicangdu/vue2-manage#183]
![Snipaste_2021-04-11_10-10-04](https://user-images.githubusercontent.com/46715367/114289923-2aeb9000-9aae-11eb-844a-3ad5a984eccd.jpg)

**Comment by bailicangdu** [comment]
已修复------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月11日(星期天) 上午10:11
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[bailicangdu/vue2-manage] 大佬，仿饿了么移动端的接口都挂了 (#183)

**Comment by Barryhuan** [comment]
感谢大佬，膜拜



在 2021-04-11 11:07:40，"cangdu" ***@***.***> 写道：

已修复------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月11日(星期天) 上午10:11
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[bailicangdu/vue2-manage] 大佬，仿饿了么移动端的接口都挂了 (#183)

**Comment by Barryhuan** [comment]
大佬，接口又挂了
![Snipaste_2021-04-29_17-26-53](https://user-images.githubusercontent.com/46715367/116530012-1f062780-a910-11eb-9aaf-4dbdf1891a5d.jpg)

**Comment by bailicangdu** [comment]
已修复 @Barryhuan

**Comment by Barryhuan** [comment]
有一次麻烦大佬了，3Q



在 2021-04-29 17:49:04，"cangdu" ***@***.***> 写道：

已修复 @Barryhuan

**Comment by bailicangdu** [comment]
应该的，谢谢你的通知👍
