### ISSUE TITLE
关于登录

### ISSUE THREAD

**Issue by huhongliang** [bailicangdu/vue2-manage#23]
我这边开发是用的您的这个项目，登录这块我看到登陆后是有保存cookie的但是我找了相关的文件没找到这个设置操作，还有就是登陆后关闭浏览器再重新打开项目，这个流程向后台验证的时候也没有找到操作cookie和向后台发送的参数，用vue开发的时间不久，希望大神能指点一下这个操作实在哪个地方

**Comment by bailicangdu** [comment]
这个cookie其实是session。是由后台发送给前台，自动保存在cookie中。前台发送请求的时候会自动带上session，后台拿到session，取出对应的用户信息

**Comment by zhaohxfight** [comment]
您好，关于登录，发现一个小bug 就是由于自动保存cookie 引起的，我觉得应该在登录之前要执行一个清除cookie的操作，不然我切换用户进入页面还是上一个用户的信息，必须刷新才能变成新用户信息。
