### ISSUE TITLE
yarn 下载出现的四个问题

### ISSUE THREAD

**Issue by above-lilili** [bailicangdu/vue2-manage#81]
warning autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning nightwatch > proxy-agent > socks-proxy-agent > socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
warning sinon > formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead
warning webpack-bundle-analyzer > bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
[3/5] Fetching packages...

请问这个四个问题我要如何来解决

**Comment by bailicangdu** [comment]
这是警告，可以忽略
