### ISSUE TITLE
商品无法加入购物车

### ISSUE THREAD

**Issue by 1576316115** [bailicangdu/vue2-manage#83]
![image](https://user-images.githubusercontent.com/30398731/43843501-4e555b58-9b5a-11e8-9d60-0fed3794b80b.png)
![image](https://user-images.githubusercontent.com/30398731/43843574-78f0c67c-9b5a-11e8-9088-316bff04f6dc.png)
console没有任何报错，望解决。谢谢！

**Comment by 1576316115** [comment]
点击“+”按钮没有反馈。

**Comment by bailicangdu** [comment]
我也刚发现这个问题，有时间会解决一下

**Comment by 1576316115** [comment]
好的

**Comment by jooper** [comment]
前端框架有缓存嘛 ?   我刷新页面发现没有去调用服务器接口 ，  估计要刷5，6次会叫一次数据库接口
