### ISSUE TITLE
商铺信息更新失败

### ISSUE THREAD

**Issue by Deemooo** [bailicangdu/vue2-manage#85]
你好，在本地启动**vue2-manage**，商铺列表中的编辑功能无效。

1. 具体表现为提示“更新商铺信息成功”，但是获取的商铺列表中对应行的数据未更新。
2. 对应的代码文件为**shopList.vue**

**Comment by bailicangdu** [comment]
应该是数据缓存导致的

**Comment by Deemooo** [comment]
请问您指的是前端还是后端？前端的话应该是可以排除的，因为每次表格的数据容器都会被清空后再添加。
