### ISSUE TITLE
没有统计图引入的echarts文件夹

### ISSUE THREAD

**Issue by BaYunmo-Lry** [bailicangdu/vue2-manage#86]
在tendency.vue和visitorPie.vue文件中，我看到有很多引入echarts里的文件，但你提供的代码中没有这个文件夹
![1535081892](https://user-images.githubusercontent.com/34303827/44563769-46d18480-a792-11e8-8b89-09879947abd8.jpg)

**Comment by bailicangdu** [comment]
这是从node_modules中引入的

**Comment by BaYunmo-Lry** [comment]
哦哦，明白了
