### ISSUE TITLE
麻烦给解决下吧，卡在这里很久了！

### ISSUE THREAD

**Issue by zhaoxiang2018** [bailicangdu/vue2-manage#88]
一直提示 ‘尚未登录或者session失效’ admin/info接口报504错误，拿不到商家列表数据，但是查看数据库是添加进去的。

**Comment by zhaoxiang2018** [comment]
admin/info接口报504错误  就这一个

**Comment by zhaoxiang2018** [comment]
今天打开 又好了！！奇怪！

**Comment by KendraZhi** [comment]
相同的问题，目前还没好~   希望帮忙分析下可能是哪的问题
