### ISSUE TITLE
登陆页面输入账号密码报错

### ISSUE THREAD

**Issue by 597796340** [bailicangdu/vue2-manage#89]
message:"表单信息错误"
status:0
type:"FORM_DATA_ERROR"

await login({user_name: this.loginForm.username, password: this.loginForm.password});
字段没有错吧？

**Comment by 597796340** [comment]
可以获取管理员信息，但就登录的时候报错

**Comment by zhudongsheng** [comment]
登录账号和密码是什么啊？
