### ISSUE TITLE
如何启动

### ISSUE THREAD

**Issue by winnneror** [bailicangdu/vue2-manage#90]
你好，我将你的代码clone下来后再本地无法启动

**Comment by bailicangdu** [comment]
具体保什么错误信息呢

**Comment by winnneror** [comment]
> 具体保什么错误信息呢

你好，我想问问项目如何跑起来，是需要命令行启动吗？什么命令呢？ 在read.md文件上没有找到

**Comment by winnneror** [comment]
> 具体保什么错误信息呢

命令  npm run dev 和npm run local  提示  'cross-env' 不是内部或外部命令，也不是可运行的程序；,
请问有使用文档吗？

**Comment by liuguangsen0409** [comment]
> > 具体保什么错误信息呢
> 
> 命令 npm run dev 和npm run local 提示 'cross-env' 不是内部或外部命令，也不是可运行的程序；,
> 请问有使用文档吗？

安装依赖了吗？npm install或者yarn install（推荐yarn）安装依赖 然后通过yarn run dev启动项目 不是看read.md 看package.json中的scripts

**Comment by wangqiaozhi** [comment]
我也遇到的这个问题，用npm run都试过了，不可以

**Comment by Kabobi** [comment]
安装不上依赖 总是最后就报错 网络问题吗

**Comment by Kabobi** [comment]
安装不上依赖 总是最后就报错

**Comment by xumeihong** [comment]
'cross-env' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

我用npm install 安装依赖了  然后用npm run dev 运行  但是报了上面的错误  跑不起来

**Comment by szhang6** [comment]
试试cnpm install  安装


| |
Steven
邮箱：zxxsteven@163.com
|

Signature is customized by Netease Mail Master

在2018年11月09日 20:35，Kabob 写道：

安装不上依赖 总是最后就报错 网络问题吗

**Comment by xumeihong** [comment]
> 试试cnpm install 安装 | | Steven 邮箱：zxxsteven@163.com | Signature is customized by Netease Mail Master 在2018年11月09日 20:35，Kabob 写道： 安装不上依赖 总是最后就报错 网络问题吗 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

cnpm install   已解决我都问题  已成功跑起来 谢谢
