### ISSUE TITLE
很多错误信息,我也没能跑起来, mac , 

### ISSUE THREAD

**Issue by imouou** [bailicangdu/vue2-manage#91]
你好, 请问后台能跑起来,但登录不进去, 默认是8001, 打开会自动跳转到8002, 已经改了 dev-server.js 为8002, 还是跑不起来.

Failed to load resource: the server responded with a status of 504 (Gateway Timeout)
index.js?e3b1:29 您尚未登陆或者session失效
login:1 Failed to load resource: the server responded with a status of 504 (Gateway Timeout)
fetch.js?caf5:3 Uncaught (in promise) Error: SyntaxError: Unexpected token E in JSON at position 0
    at Object._callee$ (fetch.js?caf5:3)
    at tryCatch (runtime.js?f2a0:62)
    at Generator.invoke [as _invoke] (runtime.js?f2a0:296)
    at Generator.prototype.(:8002/anonymous function) [as throw] (webpack-internal:///196:114:21)
    at step (asyncToGenerator.js?b825:17)
    at eval (asyncToGenerator.js?b825:30)

**Comment by bailicangdu** [comment]
运行的命令是什么呢，run dev 还是  run local

**Comment by imouou** [comment]
Error occured while trying to proxy to: localhost:8002/admin/info
Error occured while trying to proxy to: localhost:8002/admin/login  
登录不进去,可以跑起来

**Comment by wangqiaozhi** [comment]
![image](https://user-images.githubusercontent.com/26948820/47769574-4ec01e80-dd17-11e8-807d-f6ff323a922b.png)

**Comment by wangqiaozhi** [comment]
在window7上一直启动不了，找了好久，都么有找到答案，哪个大神告诉我怎么解决啊
