### ISSUE TITLE
npm run build 时候报错 什么原因？

### ISSUE THREAD

**Issue by baxibaba** [bailicangdu/vue2-manage#96]
![image](https://user-images.githubusercontent.com/41287049/47610197-e278bd00-da81-11e8-96fe-38a5848e8e4d.png)

**Comment by napster99** [comment]
同样的问题，求解答

**Comment by napster99** [comment]
已解决 time-formater es6格式转下

**Comment by wangchong19940101** [comment]
@napster99 跪求解决方法
